import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import axios from "axios";
import { getCookie } from "cookies-next";
import Nav from "./components/nav";

const inter = Inter({ subsets: ["latin"] });

export default function Home(props) {
  console.log(props);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav/>
      { props?.data?.session && (<main className={`${styles.main} ${inter.className}`}>
        <h1>Hello World</h1>
      </main>)}
    </>
  );
}

export const getServerSideProps = async ({ req, res }) => {
  const result = await axios.get(
    `${req.headers["x-forwarded-proto"]}://${req.headers.host}/api/auth/login`,
    {
      withCredentials: true,
      headers: {
        Cookie: req.headers.cookie,
      },
    }
  );
  
  // console.log(res);
  return {
    props: {
      data: result?.data,

      csrf: getCookie("_csrf", { req, res }) || {},
    },
  };
};
